name: Automatic build

on:
  push:
    branches:
      - main  # Change to your main branch name if different
  pull_request:
    branches:
      - main  # Change to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]  # Specify the Node.js versions you want to test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install fuse and libfuse2
      run: sudo apt-get update && sudo apt-get install -y fuse libfuse2

    - name: Install dependencies
      run: npm install

    - name: Install electron-builder
      run: npm install electron-builder --save-dev

    - name: Build the app
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run dist

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/*.AppImage
        asset_name: $(basename ${{ runner.temp }}/dist/*.AppImage)
        asset_content_type: application/zip

